[Interface]
PrivateKey = [INSERT_YOUR_PHONE_PRIVATE_KEY_HERE]
Address = 10.0.0.2/24
DNS = 10.0.0.1

[Peer]
PublicKey = 7d7IAxPBCu3KDJ6oTly4g7+/u3vtVd+DAXkBRpVC5lg=
Endpoint = [YOUR_SERVER_PUBLIC_IP_HERE]:51820
AllowedIPs = 0.0.0.0/0

